Esta é uma linha de texto para explicar o que vai abaixo

In [1]:

nomes = ['Jose', 'Maria', 'Antonio', 'Jesus']
idades = [17,25,12,33]
cidades=['rio', 'pernambuco', 'caxias', 'nazare']
pessoas= {
        'nome': nomes,
        'idade': idades,
        'cidade': cidades
}

#a,b,c* =pessoas ['idade']
for k,v in enumerate (pessoas['nome']):
    
    if (v=='Maria'):
        print (pessoas['idade'][k])

25

In [4]:
import pandas  as pd
dados = pd.DataFrame(pessoas)
pessoas

{'nome': ['Jose', 'Maria', 'Antonio', 'Jesus'],
 'idade': [17, 25, 12, 33],
 'cidade': ['rio', 'pernambuco', 'caxias', 'nazare']}

In [7]:
dados[dados['idade']<18]

      nome  idade  cidade
0     Jose     17     rio
2  Antonio     12  caxias

In [11]:
dados.head(10)

,Company,Company Score,Job Title,Location,Date,Salary
0,ViewSoft,4.8,Software Engineer,"Manassas, VA",8d,$68K - $94K (Glassdoor est.)
1,Workiva,4.3,Software Support Engineer,Remote,2d,$61K - $104K (Employer est.)
2,"Garmin International, Inc.",3.9,C# Software Engineer,"Cary, NC",2d,$95K - $118K (Glassdoor est.)
3,Snapchat,3.5,"Software Engineer, Fullstack, 1+ Years of Expe...","Los Angeles, CA",2d,$97K - $145K (Employer est.)
4,Vitesco Technologies Group AG,3.1,Software Engineer,"Seguin, TX",2d,$85K - $108K (Glassdoor est.)
5,Spotify,3.9,Backend Engineer II,"New York, NY",1d,$123K - $175K (Employer est.)
6,Infor,4.0,Associate Software Engineer,"Alpharetta, GA",7d,$77K - $94K (Glassdoor est.)
7,Amerisoft Corporation,5.0,Software Developers,"Farmington Hills, MI",30d+,$71K - $100K (Glassdoor est.)
8,WHOOP,3.3,"Software Engineer II (Backend, Health)","Boston, MA",10d,$94K - $148K (Glassdoor est.)
9,PFF,4.2,Sr. Software Engineer,Remote,1d,$147K - $189K (Employer est.)

In [13]:
dados.tail()

,Company,Company Score,Job Title,Location,Date,Salary
860,Westchester Community College,NaN,Software Development Engineer in Test,"San Francisco, CA",30d+,NaN
861,DPS Telecom,NaN,Software & System Dev. Sr. Engineer,"Raymond, OH",30d+,NaN
862,Roblox,NaN,Software Engineer II,"Valhalla, NY",3d,NaN
863,OpenAI,NaN,Embedded Software Engineer (Entry-Level),"Lake Hopatcong, NJ",2d,NaN
864,"Akina, Inc.",NaN,Senior Software Engineer - App Orchestration,"San Mateo, CA",30d+,NaN
865,RXO,NaN,"Software Engineer, Machine Learning Compute","San Francisco, CA",6d,NaN
866,Infosys,NaN,Software Engineer - 3 (Apache NiFi),"Annapolis Junction, MD",18d,NaN
867,Medtronic,NaN,Senior Software Engineer,"Southfield, MI",19d,NaN
868,NaN,NaN,Junior Python Developer,"Charlotte, NC",2d,NaN
869,NaN,NaN,GUI Software Engineer II - Surgical Robotics,"Boston, MA",10d,NaN

In [14]:
dados.sample(10)

,Company,Company Score,Job Title,Location,Date,Salary
155,Rocket Software,4.3,Machine Learning Software Engineer,Massachusetts,3d,$138K - $294K (Employer est.)
476,PACCAR,4.2,Python Engineer,"Annapolis Junction, MD",10d,$160K - $170K (Employer est.)
541,Volvo Group,3.9,Software Engineer - Level 1 (RR) RRTN-8319,"Annapolis Junction, MD",30d+,$117K - $216K (Employer est.)
480,Lawrence Berkeley National Laboratory,3.6,2024 Associate Software Engineer - Linthicum MD,"Linthicum, MD",1d,$92K - $116K (Glassdoor est.)
413,Space Coast Intelligent Solutions,3.9,ServiceNow Software Engineer,"Washington, DC",9d,$69K - $103K (Employer est.)
562,"Hawaiian Airlines, Inc.",3.2,Staff Software Engineer - Documents,United States,2d,$80K - $123K (Glassdoor est.)
806,Spotify,NaN,Senior Java Engineer,"San Rafael, CA",6d,NaN
500,Bose,4.1,"Software Quality Assurance Engineer (Level 6),...",United States,11d,$155K - $221K (Employer est.)
730,Federal Reserve Bank of Boston,4.1,Experienced Front-End Engineer,"Fort Collins, CO",14d,$81K - $109K (Glassdoor est.)
387,Amex,4.3,Technical Support Engineer (Endpoint Software),Virginia,9d,$100K - $250K (Employer est.)

In [15]:
dados.columns

Index(['Company', 'Company Score', 'Job Title', 'Location', 'Date', 'Salary'], dtype='object')

In [16]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 870 entries, 0 to 869
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        868 non-null    object
 1   Company Score  789 non-null    float64
 2   Job Title      870 non-null    object
 3   Location       857 non-null    object
 4   Date           870 non-null    object
 5   Salary         764 non-null    object
dtypes: float64(1), object(5)
memory usage: 40.9+ KB

In [23]:
dados.Location.isnull().value_counts()

Location
False    857
True      13
Name: count, dtype: int64

In [26]:
dados.Location.value_counts().head(10)

Location
United States             48
Remote                    39
Annapolis Junction, MD    35
San Francisco, CA         28
Seattle, WA               28
San Jose, CA              20
Boston, MA                20
New York, NY              18
Bellevue, WA              12
Atlanta, GA               12
Name: count, dtype: int64

In [27]:
dados.Location.value_counts()[:20]

Location
United States             48
Remote                    39
Annapolis Junction, MD    35
San Francisco, CA         28
Seattle, WA               28
San Jose, CA              20
Boston, MA                20
New York, NY              18
Bellevue, WA              12
Atlanta, GA               12
Austin, TX                12
Chicago, IL               12
Washington, DC            10
Dallas, TX                 9
Phoenix, AZ                9
Columbia, MD               9
Los Angeles, CA            9
Santa Clara, CA            8
Fort Meade, MD             8
Charlotte, NC              7
Name: count, dtype: int64

In [28]:
dados.isnull().sum()

Company            2
Company Score     81
Job Title          0
Location          13
Date               0
Salary           106
dtype: int64

In [29]:
dados_limpos = dados.dropna(how='any')
dados_limpos

,Company,Company Score,Job Title,Location,Date,Salary
0,ViewSoft,4.8,Software Engineer,"Manassas, VA",8d,$68K - $94K (Glassdoor est.)
1,Workiva,4.3,Software Support Engineer,Remote,2d,$61K - $104K (Employer est.)
2,"Garmin International, Inc.",3.9,C# Software Engineer,"Cary, NC",2d,$95K - $118K (Glassdoor est.)
3,Snapchat,3.5,"Software Engineer, Fullstack, 1+ Years of Expe...","Los Angeles, CA",2d,$97K - $145K (Employer est.)
4,Vitesco Technologies Group AG,3.1,Software Engineer,"Seguin, TX",2d,$85K - $108K (Glassdoor est.)
...,...,...,...,...,...,...
759,OpenAI,3.1,Apprentice ETL Software Engineer,"Elkridge, MD",30d+,$160K - $385K (Employer est.)
760,NCR Atleos,3.9,"Software Engineer, Tool & Infrastructure, Reli...","Palo Alto, CA",1d,$222K (Employer est.)
761,Electronic Warfare Associates,3.8,"Software Engineer, Engineering Acceleration","San Francisco, CA",5d,$82K - $118K (Glassdoor est.)
762,"BillGO, Inc.",3.3,ATM Software Engineer (Level III),"Frisco, TX",30d+,$69K - $107K (Glassdoor est.)
763,Genesys,3.6,Software Engineer,"Mount Laurel, NJ",30d+,$95K - $143K (Employer est.)

In [30]:
dados.isnull().sum()
dados_limpos = dados.dropna(how='any')
dados_limpos

,Company,Company Score,Job Title,Location,Date,Salary
0,ViewSoft,4.8,Software Engineer,"Manassas, VA",8d,$68K - $94K (Glassdoor est.)
1,Workiva,4.3,Software Support Engineer,Remote,2d,$61K - $104K (Employer est.)
2,"Garmin International, Inc.",3.9,C# Software Engineer,"Cary, NC",2d,$95K - $118K (Glassdoor est.)
3,Snapchat,3.5,"Software Engineer, Fullstack, 1+ Years of Expe...","Los Angeles, CA",2d,$97K - $145K (Employer est.)
4,Vitesco Technologies Group AG,3.1,Software Engineer,"Seguin, TX",2d,$85K - $108K (Glassdoor est.)
...,...,...,...,...,...,...
759,OpenAI,3.1,Apprentice ETL Software Engineer,"Elkridge, MD",30d+,$160K - $385K (Employer est.)
760,NCR Atleos,3.9,"Software Engineer, Tool & Infrastructure, Reli...","Palo Alto, CA",1d,$222K (Employer est.)
761,Electronic Warfare Associates,3.8,"Software Engineer, Engineering Acceleration","San Francisco, CA",5d,$82K - $118K (Glassdoor est.)
762,"BillGO, Inc.",3.3,ATM Software Engineer (Level III),"Frisco, TX",30d+,$69K - $107K (Glassdoor est.)
763,Genesys,3.6,Software Engineer,"Mount Laurel, NJ",30d+,$95K - $143K (Employer est.)

In [31]:
dados.shape

(870, 6)

In [32]:
dados[dados['Company']=='Tesla']

,Company,Company Score,Job Title,Location,Date,Salary
618,Tesla,4.2,Software Engineer - Innovation,"Saint Paul, MN",10d,$182K - $244K (Glassdoor est.)
652,Tesla,4.2,Senior Software Development Engineer,"San Jose, CA",11d,$74K - $109K (Glassdoor est.)
758,Tesla,4.1,Junior Java Software Engineer,"Fort Meade, MD",30d+,$234K - $284K (Employer est.)

In [43]:
import re
def limpa_titulo(titulo:str):
    return re.split(r'\(|-',titulo)[0].strip()
dados ['Main Job'] = dados ['Job Title'].apply (limpa_titulo)

def converte_data (data_str:str):
    if 'd' in data_str:
        return int (data_str.replace('d','').replace('+','').strip())
    if 'h' in data_str:
        return int (data_str.replace('h','').replace('+','').strip())/24
    if 'w' in data_str:
        return int (data_str.replace('w','').replace('+','').strip())*7
    else:
        return None
    
dados ['Days Post'] = dados ['Date'].apply(converte_data)

def converte_salario (salario_str):
    salario_range = re.findall (r'\$([\dK])', salario_str)
    salario_range = [int(s.replace ('K',''))*1000 for s in salario_range]
    if len (salario_range)==2:
        return sum (salario_range)/2
    else:
        return None
    
dados ['Salary'] = dados ['Salary'].astype(str)
dados ['Salario Medio']=dados['Salary'].apply(converte_salario)

dados

,Company,Company Score,Job Title,Location,Date,Salary,Main Job,Days Post,Salario Medio
0,ViewSoft,4.8,Software Engineer,"Manassas, VA",8d,$68K - $94K (Glassdoor est.),Software Engineer,8.0,7500.0
1,Workiva,4.3,Software Support Engineer,Remote,2d,$61K - $104K (Employer est.),Software Support Engineer,2.0,3500.0
2,"Garmin International, Inc.",3.9,C# Software Engineer,"Cary, NC",2d,$95K - $118K (Glassdoor est.),C# Software Engineer,2.0,5000.0
3,Snapchat,3.5,"Software Engineer, Fullstack, 1+ Years of Expe...","Los Angeles, CA",2d,$97K - $145K (Employer est.),"Software Engineer, Fullstack, 1+ Years of Expe...",2.0,5000.0
4,Vitesco Technologies Group AG,3.1,Software Engineer,"Seguin, TX",2d,$85K - $108K (Glassdoor est.),Software Engineer,2.0,4500.0
...,...,...,...,...,...,...,...,...,...
865,RXO,NaN,"Software Engineer, Machine Learning Compute","San Francisco, CA",6d,nan,"Software Engineer, Machine Learning Compute",6.0,NaN
866,Infosys,NaN,Software Engineer - 3 (Apache NiFi),"Annapolis Junction, MD",18d,nan,Software Engineer,18.0,NaN
867,Medtronic,NaN,Senior Software Engineer,"Southfield, MI",19d,nan,Senior Software Engineer,19.0,NaN
868,NaN,NaN,Junior Python Developer,"Charlotte, NC",2d,nan,Junior Python Developer,2.0,NaN
869,NaN,NaN,GUI Software Engineer II - Surgical Robotics,"Boston, MA",10d,nan,GUI Software Engineer II,10.0,NaN

In [10]:
dados=pd.read_csv('job.csv')
dados

,Company,Company Score,Job Title,Location,Date,Salary
0,ViewSoft,4.8,Software Engineer,"Manassas, VA",8d,$68K - $94K (Glassdoor est.)
1,Workiva,4.3,Software Support Engineer,Remote,2d,$61K - $104K (Employer est.)
2,"Garmin International, Inc.",3.9,C# Software Engineer,"Cary, NC",2d,$95K - $118K (Glassdoor est.)
3,Snapchat,3.5,"Software Engineer, Fullstack, 1+ Years of Expe...","Los Angeles, CA",2d,$97K - $145K (Employer est.)
4,Vitesco Technologies Group AG,3.1,Software Engineer,"Seguin, TX",2d,$85K - $108K (Glassdoor est.)
...,...,...,...,...,...,...
865,RXO,NaN,"Software Engineer, Machine Learning Compute","San Francisco, CA",6d,NaN
866,Infosys,NaN,Software Engineer - 3 (Apache NiFi),"Annapolis Junction, MD",18d,NaN
867,Medtronic,NaN,Senior Software Engineer,"Southfield, MI",19d,NaN
868,NaN,NaN,Junior Python Developer,"Charlotte, NC",2d,NaN
869,NaN,NaN,GUI Software Engineer II - Surgical Robotics,"Boston, MA",10d,NaN